name: Quarto Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: raphateixeira/.github/.github/workflows/quarto-publish.yml@main
    with:
      output_dir: "docs"
